version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env
    volumes:
      - db_value:/var/lib/postgresql/data/
  
  backend:
    image: koan24/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static_value:/backend_static
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: koan24/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
       - static_value:/frontend_static
    depends_on:
      - backend

  nginx:
    image: koan24/foodgram_gateway:latest
    env_file: .env
    restart: always
    volumes:
      - static_value:/staticfiles/
      - media_value:/media
    ports:
      - 8000:80
    depends_on:
      - backend
