version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - db_value:/var/lib/postgresql/data
  
  backend:
    image: koan24/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: koan24/foodgram_frontend:latest
    env_file: .env
    volumes:
       - ../frontend/:/app/result_build/

  nginx:
    image: koan24/foodgram_gateway:latest
    env_file: .env
    restart: always
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - 8000:80
    depends_on:
      - backend
