# Generated by Django 3.2.15 on 2023-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmountOfIngridient',
            new_name='AmountOfIngredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Изображние'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='#FF0000', max_length=7, unique=True, verbose_name='Цветовой HEX-код'),
        ),
    ]
